Hello World,

My name is Ingy döt Net. I am an "Acmeist Programmer"<http://www.acmeism.org>. I want to spend most of my time in this life working on various projects that intrigue me. All of these projects are completely open and available to everyone. Some of them are even useful.

In order to pursue this desire, I have decided that I need to be *Free*. To me, being Free means doing what _you_ want to do, practicing what _you_ believe is right, following _your_ heart, and fulfilling _your_ dreams. Every day of _your_ life.

When a person spends their time on the interest of others, I label this being *Bound*. Most people are Bound by a job, where they trade their time and creative resources for money to pay for things they need to live. A person can spend their time being Bound or being Free. Obviously, being Bound allows you to trade your time for money, but rarely can you trade your Free time for money. 

I want to be Free. I have tried to organize my life to use my resources wisely, such that I can spend the least amount of my time being Bound. If I had my druthers, I would never again be Bound to a job where I did work that I would not do if I was Free. Instead I would spend my time and creative energy working on the things I believe in. Here is a list of some of my more ambitious projects, all of which I believe in:

* "Acmeism"<http://www.acmeism.org> -- A Philosophy
* "C'Dent"<http://www.cdent.org> -- An Acmeist Programming Language
* "TestML"<http://www.testml.org> -- A Unit Test Framework
* "Stardoc"<http://www.stardoc.org> -- A Portable Documentation Framework
* "YAML"<http://www.yaml.org> -- A Data Serialization Language
* "JSYNC"<http://www.jsync.org> -- Another Data Serialization Language
* "Pegex"<http://www.pegex.org> -- An Acmeist PEG Parser Generation Language
* "CogBase"<http://www.cogbase.org> -- An Object Database
* "XLog"<http://xlogger.org> -- A New Kind of Blogging
* "Kwiki"<http://www.kwiki.org> -- A Wiki
* "Jemplate"<http://www.jemplate.net> -- A Portable Template Language
* "Wikiwyg"<http://www.wikiwyg.net> -- A Richtext/Wikitext Wiki Editor
* NoCore -- Computing without CPUs
* HelloWord -- Basic Language Learning Software

All of the programming source code for these projects and many others is Freely available "my GitHub page"<http://github.com/ingydotnet/> and also distributed on services like "CPAN"<http://search.cpan.org/~ingy/> and "PyPI"<http://pypi.python.org/pypi>, as appropriate. As often as possible, I give Free presentations about these projects at conferences, workshops and user group meetings around the world, to people of all programming backgrounds. I spend time talking and working with them to further these and similar works. 

Can you help me be Free all the time? Maybe you are a company who uses some of these projects. Maybe you are a philanthopist who believes in the tenets of Acmeism. Maybe you are one who can afford to offer me the equivalent of a decent salary, so that I may put all my effort into this work, and continue to evangelize it. Are you? Will you? If Yes, contact me. In the meantime I will be spending my Free time on these exciting things.

Freely Yours, Ingy döt Net
